apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: marquinhusbill/gitflow
  newTag: 40097ae7d24a460022d5ea29bccde54b78900c1a
