name: CD Gitops

on:
  push:
    branches:
      - main
      - develop

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/gitflow
          tags: ${{github.sha}},latest
          push: true
